### ISSUE TITLE
bug - Poisson distribution - Fetch argument None has invalid type <class 'NoneType'>

### ISSUE THREAD

**Issue by VertigoX64** [PGM-Lab/InferPy#110]
Platform : Python 3.6.5 X64 on macOS Mojave 10.14.3
Associated Libraries: TensorFlow 1.7.1 , Numpy 1.14.3
Inferpy version: 0.2.1

----------------------------
Upon running 
>>  inferpy._models_.**Poisson**(2).**sample**(2)
This error trace is produced
![image](https://user-images.githubusercontent.com/19937537/51934520-06e58c00-2419-11e9-84f7-57be60c7683d.png)

**Comment by rcabanasdepaz** [comment]
Hi,
thank you for reporting this issue. We have already detected the cause of this bug. We will give you a solution in the next hours.

**Comment by VertigoX64** [comment]
Thank you sir.

**Comment by rcabanasdepaz** [comment]
A new version with this bug fixed has been released (0.2.2). You can upgrade your local
package from pip. See the following notebook: 

https://colab.research.google.com/drive/1-l16hKSVIO_twGCZXwsKGq_9rUQSydIj
