### ISSUE TITLE
Make optional the RVs name outside a probmodel

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#121]
The name of the rvs is required to check the dependencies. But in some cases outside a probmodel, it could be omitted or used a default one.

This should be implemented after #117

**Comment by jcozar87** [comment]
It is already implemented in this way. I think that the problem was related to creating a default 
probmodel if datamodel is used out of this context. I will close this issue for now, as it seems it does not happen anymore.
