### ISSUE TITLE
set_values for tf.variables

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#133]
Find a way to fix the values of the tf.variables in a model (or the paramaters). Then, these could also be made non-trainable (i.e., using tf.stop_gradient)

```
@inf.probmodel
def model():
    theta = tf.Variable(..., name="theta")
    x = inf.Normal(....)



m = model()

m.sample(theta=5)
```

A possible use-case: VAE with non-probabilistic weights (in sampling or in the log-likelihood computation).

**Comment by jcozar87** [comment]
We have decided to follow a similar approach than Keras: we are going to use a global graph and session, and all the learning processes are executed in such session. Therefore, we do not need to save, load or set the values for `tf.Variables`.
