### ISSUE TITLE
input parameter and property for setting the batch_shape

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#136]
The following code

```
w = inf.Normal(np.zeros([k,d]), 1, name="w")

assert w.shape == [k,d]
assert w.sample_shape == []
assert assert w.dim == [k,d] 
assert assert w.dim == w.batch_shape
```

is equivalent to

```
w = inf.Normal(0, 1, dim =[k,d]) 

assert w.shape == [k,d]
assert w.sample_shape == []
assert assert w.dim == [k,d] 
assert assert w.dim == w.batch_shape
```

Note that the scalar parameters are broadcasted to the dimensions [k,d].

Instead of getting the batch_shape from the distribution parameters, these are obtained from the input parameter dim. We might call it _dim_ instead of _batch_shape_ for making it more understandable. As the batch_shape is a property from edward RVs, this can be already obtained. Yet, for keeping a coherence in the names, we might implement a property dim:

```
@property
def dim(self):
    return self.batch_shape
```

**Comment by jcozar87** [comment]
Closed in #bd906331b79fa95ffb28beff8bc2763668b580e9
