### ISSUE TITLE
Bayesian deep learning

### ISSUE THREAD

**Issue by alexv1247** [PGM-Lab/InferPy#141]
I just wanted to know when the Bayesian deep learning with keras support is getting implemented? It would be a huge step for inferpy, since no other library can perfoam that in an easy manner. Especially the support for Bayesian LSTM would be awesome, because tensorflow probability has no support for that by now!

**Comment by rcabanasdepaz** [comment]
Hi!
First of all thanks for your interest. We have been working on the integration with Edward2 and the latest versions of tensorflow. No later than next week, we hope to launch InferPy 1.0 which will allow the definition of models containing DNNs (using tf.layers or keras). 

As an advancement, you might check the following notebook.

https://colab.research.google.com/drive/1xDCY8qhOAiTovO_g8r1bhqyYWtAz9OTC

**Comment by alexv1247** [comment]
That sounds awesome. I am looking forward!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
