### ISSUE TITLE
Wrong sample_shape of RVs outside a model

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#147]
The sample_shape of a RV defined outside a model is empty while inside is always [1]. The shape should be the same. Consider this example: 

```
# required pacakges
import inferpy as inf
import tensorflow as tf


@inf.probmodel
def linear_reg(d):
    w0 = inf.Normal(0, 1, name="w0")
    w = inf.Normal(0, 1, batch_shape=[d], name="w")

    with inf.datamodel():
        x = inf.Normal(5, 2, batch_shape=d, name="x")
        y = inf.Normal(w0 + x @ tf.transpose(w), 1.0, name="y")

m = linear_reg(6)
w_in = m.vars["w"]
w_out = inf.Normal(0, 1, batch_shape=[6])

w_in.sample_shape   # [1]
w_out.sample_shape  # []


```

**Comment by jcozar87** [comment]
This behaviour is on purpose. Random Variables in probabilistic models ALWAYS have a sample shape, at least equals to 1. This is done to make it easy to manage the `shape=(sample_shape, batch_shape, event_shape)`, and to generalize the behaviour of many functions (sample, log_prob, predict, ...)

**Comment by jcozar87** [comment]
Related to #150 , we could force `sample_shape` to be at least 1 just inside `datamodel`s. I think this has more sense. What do you think?
