### ISSUE TITLE
The documentation is full of typos and the references are not working

### ISSUE THREAD

**Issue by nbro** [PGM-Lab/InferPy#197]
I was reading the documentation for InferPy. It is full of typos and the references are not working properly. For example, in https://inferpy.readthedocs.io/en/0.0.3/notes/guideinference.html, you write "infererence" rather than "inference". You also write "Look at ? for a detailed description of the available inference algorithms". This is not the only page of the documentation that contains typos.

**Comment by rcabanasdepaz** [comment]
Hi,
thanks for your feedback. But you are looking to the version 0.0.3, a very old version (currently we are at 1.2.3). For the most resent documentation, just select it in the left-side menu or open the following link: 
https://inferpy.readthedocs.io/en/latest/

**Comment by nbro** [comment]
@rcabanasdepaz I've found some typos even in the docs corresponding to the latest version of the package. For example, in https://inferpy.readthedocs.io/en/latest/notes/guideinference.html and https://inferpy.readthedocs.io/en/latest/notes/bayesianNN.html, there are some typos. In the page https://inferpy.readthedocs.io/en/latest/notes/guidebayesian.html, you're using `tf.layers`, which is deprecated, even though you suggest the alternative Keras' layers.

**Comment by rcabanasdepaz** [comment]
We will review the typos for the next version.

InferPy works with ``tf.layers``,  ``tf.keras`` or even with the stand-alone keras package. Actually, at the end of the page you mentioned, you have an example with ``tf.keras``. https://inferpy.readthedocs.io/en/latest/notes/guidebayesian.html

Moreover, in the next release it will be compatible with keras models such as ``tf.keras.Sequential``
