### ISSUE TITLE
pip fails on install

### ISSUE THREAD

**Issue by kasper-thofte** [PGM-Lab/InferPy#208]
pip install inferpy
Collecting inferpy
  Using cached inferpy-1.3.1.tar.gz (1.6 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.12.1 (from inferpy) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0)
ERROR: No matching distribution found for tensorflow<2.0,>=1.12.1 (from inferpy)

The result is the same adding to a clean poetry environment.

**Comment by rcabanasdepaz** [comment]
Hi, it seems that you are not using the proper version of pip or python for which TensorFlow<2.0 is not available. Can you give the following information about your system?

- Operative system
- whether or not you are using a virtual environment 
- python version:  python --version
- pip version: pip -- version

**Comment by kasper-thofte** [comment]
the snappy reply is good stuff, thank you.

OS: ubuntu 16.04
python version: 3.8.1
pip version: 20.1.1

the result is the same whether using a poetry virtual environment or pip without a virtual environment as above:

poetry add inferpy
Using version ^1.3.1 for inferpy

Updating dependencies
Resolving dependencies... (0.1s)

[SolverProblemError]
Because inferpy (1.3.1) depends on tensorflow (>=1.12.1,<2.0)
 and no versions of inferpy match >1.3.1,<2.0.0, inferpy (>=1.3.1,<2.0.0) requires tensorflow (>=1.12.1,<2.0).
So, because eir depends on both tensorflow (>=2) and inferpy (^1.3.1), version solving failed.

**Comment by rcabanasdepaz** [comment]
TensorFlow<2.0 is only available for at most python 3.7.x: https://pypi.org/project/tensorflow/1.15.3/ . So try to install it with python 3.7.

We are working on making inferpy compatible with TensorFlow 2, which will solve this issue. This will be available in a future release.
