### ISSUE TITLE
Pip install system and other modules fail

### ISSUE THREAD

**Issue by RecepBlby** [PGM-Lab/InferPy#211]
Windows 10.
pip 20.2
Python 3.8.2
Hello. I have been trying to install some packages like pyautogui, pyinstaller, system but I have the same error. I have uploaded many packages before and now I couldn't find the solution. Could you please help me figure out ?

```
ERROR: Could not find a version that satisfies the requirement system (from versions: none)
ERROR: No matching distribution found for system

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
ERROR: Could not find a version that satisfies the requirement system (from versions: none)
ERROR: No matching distribution found for system
```

**Comment by rcabanasdepaz** [comment]
Hi

Our package requires TensorFlow<2.0, which  is only available for at most python 3.7.x: https://pypi.org/project/tensorflow/1.15.3/ . So try to install it with a lower version of python (3.5, 3.6 or 3.7).

We are working on making inferpy compatible with TensorFlow 2, which will solve this issue. This will be available in a future release.

**Comment by guptakmanish29** [comment]
i am getting message, module not found, despite the fact pip list command shows the packages name, as pandas & numpy work perfect, these modules giving a nightmare

**Comment by rcabanasdepaz** [comment]
Can you paste the error you get? Also it would be great to know some details on your system, such as SO, python version, versions of TF, TFP, numpy and pandas, etc.
 
I would recommend you to install it a clean virtual environment with python 3.7.x or lower.

**Comment by guptakmanish29** [comment]
Traceback (most recent call last):
  File "c:/Users/hp/Desktop/auto/test.py", line 1, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
Os: Win 10
python version : 3.8.5
TF: 2.3.0
TFP: ?? i dont know what is this
numpy : 1.19.1
pandas : 1.1.1

how to install virt. env and which one??

**Comment by guptakmanish29** [comment]
same error comes with packages tensorflow, pyinputplus also

**Comment by guptakmanish29** [comment]
![image](https://user-images.githubusercontent.com/70595002/91970334-1fc0cc80-ed35-11ea-9572-5eea355cce58.png)

**Comment by guptakmanish29** [comment]
this list comes with command pip list, see all packages installed

**Comment by rcabanasdepaz** [comment]
Your problem is that you are using a new Python version (3.8.5) which not compatible. Switch to an older version (up to 3.7.9). You can check the inferpy requirements here: https://inferpy.readthedocs.io/projects/develop/en/latest/notes/requirements.html 




Check this link for changing the python version and managing virtual environments: https://code.visualstudio.com/docs/python/environments (you might will have to install it your system). 

*TFP stands for tensorflow-probability.
