### ISSUE TITLE
Edward1 compatibility 

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#99]
We must decide if we keep the compatibility with Edward1. In that case, a problem arises: Edward1 is not compatible with TF>1.7, but for Edward2 we might need to have the latest TF version. Thus, the mode where Edward1 is used as a back-end may not set if the package version is incorrect. This will be checked in runtime.

**Comment by jcozar87** [comment]
We have determined not to keep compatibility with edward1. The InferPy 1.0 version has many modifications in structure and in functionality. Therefore, we have decided to increase the major version (from 0.X to 1.X).
